[template]
cargo_generate_version = ">=0.15.2"

[placeholders.description]
default = ""
prompt = "description:"
type = "string"

[placeholders.edition]
default = "2021"
prompt = "edition:"
type = "string"

[placeholders.homepage]
default = ""
prompt = "homepage:"
type = "string"

[placeholders.spdx-license]
default = "MIT"
prompt = "license (SPDX)"
type = "string"

[placeholders.publish]
default = true
prompt = "publish"
type = "bool"

[placeholders.readme]
default = "README.md"
prompt = "readme"
type = "string"

[placeholders.github_username]
default = ""
prompt = "github username"
type = "string"

[placeholders.workspace]
default = false
prompt = "workspace:"
type = "bool"